apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: hello-gcp
  name: hello-gcp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello-gcp
  strategy: {}
  template:
    metadata:
      labels:
        run: hello-gcp
    spec:
      containers:
      - image: gcr.io/gcp-learning-237423/hello-gcp
        name: hello-gcp
        resources: {}
status: {}
