apiVersion: v1
kind: Service
metadata:
  labels:
    run: hello-gcp
  name: hello-gcp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: hello-gcp
  type:
    LoadBalancer
status:
  loadBalancer: {}
